[package]
name = "rust-paymail-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bitcoin_hashes = "0.10.0"
hex = "0.4.3"
curl = "0.4.41"
serde_json = "1.0.71"
